stack:		.4byte 0x100400
reset:		.4byte _start
buserror:   .4byte _start
addrerror:  .4byte _start
illinst:    .4byte _start
div0:       .4byte _start
trapv:      .4byte _start
privviol:   .4byte _start
trace:      .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _start
            .4byte _int1vec
            .4byte _int2vec
            .4byte _int3vec
            .4byte _int4vec
            .4byte _int5vec
            .4byte _int6vec
            .4byte _int7vec

